# Site settings
title: Peeragogy Dashboard
description: "Peeragogy Dashboard web interface"
url: 
author:
  name: "Fabrizio Terzi"
  email: "siar.member@fsf.org"

# Build settings
baseurl: /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title

# Default values
defaults:
  -
    scope:
      path: ""
      type: "code"
    values:
      layout: "html"

# Custom variables
version: "1.1.5"
