name: Peeragogy dashboard
markdown: redcarpet
pygments: true
baseurl:Peeragogy/Peeragogy-Dashboard
language: go
sudo: false
html:
- 1.1.1
- 1.1.2
- 1.1.3
- 1.1.4
- 1.1.5
exclude: [vendor]

# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
